import React from 'react';
import {
  Search,
  Code2,
  Target,
  TrendingUp,
  Bot,
  Layout,
  Globe,
  BarChart2,
  UserCheck,
  Sparkles,
  Building2,
  Package,
  GraduationCap,
  Award,
  Layers,
  Palette,
  Cpu,
  Zap,
  CheckCircle2,
  ShieldCheck,
  FileText,
  ArrowRight,
  Mail,
  MapPin,
  Github,
  Linkedin,
  Instagram,
  Facebook,
  LucideProps,
} from 'lucide-react';

const ICON_MAP: Record<string, React.FC<LucideProps>> = {
  search: Search,
  code: Code2,
  code2: Code2,
  target: Target,
  'trending-up': TrendingUp,
  bot: Bot,
  layout: Layout,
  globe: Globe,
  'bar-chart-2': BarChart2,
  barchart2: BarChart2,
  'user-check': UserCheck,
  usercheck: UserCheck,
  sparkles: Sparkles,
  'building-2': Building2,
  building2: Building2,
  package: Package,
  'graduation-cap': GraduationCap,
  graduationcap: GraduationCap,
  award: Award,
  layers: Layers,
  palette: Palette,
  cpu: Cpu,
  zap: Zap,
  'check-circle-2': CheckCircle2,
  checkcircle2: CheckCircle2,
  'shield-check': ShieldCheck,
  shieldcheck: ShieldCheck,
  'file-text': FileText,
  filetext: FileText,
  'arrow-right': ArrowRight,
  arrowright: ArrowRight,
  mail: Mail,
  'map-pin': MapPin,
  mappin: MapPin,
  github: Github,
  linkedin: Linkedin,
  instagram: Instagram,
  facebook: Facebook,
};

export function getDynamicIcon(iconName?: string): React.FC<LucideProps> {
  if (!iconName) return Layers;
  const normalized = iconName.toLowerCase().replace(/[^a-z0-9-]/g, '').trim();
  return ICON_MAP[normalized] || ICON_MAP[normalized.replace(/-/g, '')] || Layers;
}
